#!/bin/sh

MIRROR_DIR="/net/mirror"
HTTP_DIR="/var/www/mirror"

case $1 in
	configure)

                n4d-modules enable-plugin /etc/n4d/conf.d/EpoptesFilter.json || true		

	;;
	*)
		echo "Nothing to do"
		;;
esac

#DEBHELPER#
